@extends('layouts.site')
@php($title = 'Aircon Care Plans')

@section('content')
<section class="page-hero"><div class="site-shell page-intro"><span class="eyebrow">IcyBreeze subscriptions</span><h1>Put cleaner air on the calendar</h1><p>Choose a recurring care plan for your Iligan City home. We will confirm the first visit and keep the next one ready.</p></div></section>

<section class="section subscription-form-section">
    <div class="site-shell subscription-form-layout">
        <div>
            <div class="section-heading"><span class="eyebrow">Choose your rhythm</span><h2>Simple recurring care</h2><p>Your price is based on the service and number of units you choose. No automatic card charge is created in this MVP.</p></div>
            <div class="plan-stack plan-stack-wide">
                <article class="plan-card plan-card-featured"><span class="plan-kicker">Save 10% per visit</span><div class="plan-icon"><i class="ph ph-arrows-clockwise"></i></div><h3>Quarterly Care</h3><p>Four visits a year for daily-use units and households that want a dependable routine.</p></article>
                <article class="plan-card"><span class="plan-kicker">Save 5% per visit</span><div class="plan-icon"><i class="ph ph-calendar-dots"></i></div><h3>Biannual Care</h3><p>Two visits a year for moderate-use rooms that need regular seasonal upkeep.</p></article>
            </div>
        </div>

        <form class="subscription-form-card" method="POST" action="{{ route('subscriptions.store') }}" data-subscription-form>
            @csrf
            <h2>Start a care plan</h2><p>We will review the request and confirm the first visit with you.</p>
            @if($errors->any())<div class="flash" style="margin:0 0 18px;color:#9b3a3a;background:#fff0f0;border:1px solid #f2caca"><i class="ph-fill ph-warning-circle"></i>Please review the highlighted information.</div>@endif
            <div class="field"><label>Plan</label><div class="payment-options"><div class="payment-option"><input id="plan-quarterly" type="radio" name="plan" value="quarterly_care" data-discount=".90" @checked(old('plan','quarterly_care') === 'quarterly_care') required><label for="plan-quarterly"><i class="ph ph-arrows-clockwise"></i><span><strong>Quarterly Care</strong><span>Every 3 months · save 10%</span></span></label></div><div class="payment-option"><input id="plan-biannual" type="radio" name="plan" value="biannual_care" data-discount=".95" @checked(old('plan') === 'biannual_care') required><label for="plan-biannual"><i class="ph ph-calendar-dots"></i><span><strong>Biannual Care</strong><span>Every 6 months · save 5%</span></span></label></div></div></div>
            <input type="hidden" name="service_id" value="{{ $service->id }}">
            <div class="field-grid" style="margin-top:18px"><div class="field"><label for="subscription_unit_type">Aircon unit type</label><select id="subscription_unit_type" name="aircon_unit_type_id" required>@foreach($unitTypes as $unitType)<option value="{{ $unitType->id }}" data-price="{{ $unitType->price_centavos }}" @selected((int)old('aircon_unit_type_id', $unitTypes->first()?->id) === $unitType->id)>{{ $unitType->name }} · {{ $unitType->formatted_price }}</option>@endforeach</select></div><div class="field"><label for="subscription_quantity">Matching units per visit</label><select id="subscription_quantity" name="quantity">@for($quantity=1;$quantity<=5;$quantity++)<option value="{{ $quantity }}" @selected((int)old('quantity',1)===$quantity)>{{ $quantity }} {{ Str::plural('unit',$quantity) }}</option>@endfor</select></div></div>
            <div class="subscription-estimate"><span>Estimated price per visit</span><strong data-subscription-price>—</strong></div>
            <div class="field-grid"><div class="field"><label for="next_service_date">Preferred first visit</label><input id="next_service_date" type="date" name="next_service_date" min="{{ today()->addDay()->format('Y-m-d') }}" value="{{ old('next_service_date',today()->addDays(7)->format('Y-m-d')) }}" required></div><div class="field"><label for="preferred_day">Best day</label><select id="preferred_day" name="preferred_day">@foreach(['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'] as $day)<option @selected(old('preferred_day','Saturday')===$day)>{{ $day }}</option>@endforeach</select></div><div class="field full"><label>Best arrival time</label><div class="time-grid">@foreach(['08:00','10:00','13:00','15:00'] as $time)<div class="time-option"><input id="sub-time-{{ str_replace(':','',$time) }}" type="radio" name="preferred_time" value="{{ $time }}" @checked(old('preferred_time','10:00')===$time)><label for="sub-time-{{ str_replace(':','',$time) }}">{{ \Carbon\Carbon::createFromFormat('H:i',$time)->format('g:i A') }}</label></div>@endforeach</div></div></div>
            <h3 class="form-section-title">Contact and Iligan address</h3>
            <div class="field-grid"><div class="field"><label for="first_name">First name</label><input id="first_name" name="first_name" value="{{ old('first_name') }}" required></div><div class="field"><label for="last_name">Last name</label><input id="last_name" name="last_name" value="{{ old('last_name') }}" required></div><div class="field"><label for="email">Email</label><input id="email" type="email" name="email" value="{{ old('email') }}" required></div><div class="field"><label for="phone">Mobile number</label><input id="phone" name="phone" value="{{ old('phone') }}" required></div><div class="field full"><label for="address_line">Street / building / unit</label><input id="address_line" name="address_line" value="{{ old('address_line') }}" required></div><div class="field"><label for="barangay">Barangay</label><input id="barangay" name="barangay" value="{{ old('barangay') }}" required></div><div class="field"><label for="city">City</label><select id="city" name="city"><option value="Iligan City">Iligan City</option></select></div><div class="field"><label for="postal_code">Postal code</label><input id="postal_code" name="postal_code" value="{{ old('postal_code','9200') }}"></div><div class="field"><label for="landmark">Nearby landmark</label><input id="landmark" name="landmark" value="{{ old('landmark') }}"></div>
                <div class="field full"><div class="gps-capture" data-location-fields><div class="gps-icon"><i class="ph ph-crosshair"></i></div><div><strong>Share the service location</strong><p>Optional. The approved pin is available only to the assigned technician and office team.</p><span data-location-status>No location shared yet.</span></div><button class="button button-ghost button-small" type="button" data-geolocate><i class="ph ph-map-pin"></i> Use my location</button><input type="hidden" name="latitude" value="{{ old('latitude') }}" data-latitude><input type="hidden" name="longitude" value="{{ old('longitude') }}" data-longitude><input type="hidden" name="location_consent" value="{{ old('location_consent') }}" data-location-consent></div></div>
                <div class="field full"><label for="notes">Plan notes <span style="font-weight:400">(optional)</span></label><textarea id="notes" name="notes" placeholder="Access instructions, unit concerns, or reminder preferences">{{ old('notes') }}</textarea></div>
            </div>
            <label class="terms"><input type="checkbox" name="terms" value="1" required><span>I confirm this Iligan City service request and understand the office will confirm the recurring schedule before activation.</span></label>
            <button class="button button-yellow" style="width:100%;margin-top:18px" type="submit">Request my care plan <i class="ph ph-arrow-right"></i></button>
        </form>
    </div>
</section>
@endsection
