@extends('layouts.admin')
@php($title = 'Technicians')
@section('content')
<div class="admin-top"><div><h1>Technician mobile accounts</h1><p>Create field logins, review last GPS updates, and manage account access.</p></div><a class="button button-ghost button-small" href="{{ route('technician.login') }}" target="_blank">Open technician portal <i class="ph ph-arrow-up-right"></i></a></div>
<div class="service-admin-grid">
    @foreach($technicians as $technician)<section class="service-admin-card"><div style="display:flex;justify-content:space-between;gap:12px;align-items:flex-start"><div><h2 style="margin-bottom:4px">{{ $technician->name }}</h2><span class="status-badge {{ $technician->is_active ? 'status-paid' : 'status-cancelled' }}">{{ $technician->is_active ? 'Active' : 'Disabled' }}</span></div><div class="feature-icon" style="width:46px;height:46px;font-size:23px"><i class="ph ph-identification-card"></i></div></div><div class="technician-summary"><span><i class="ph ph-calendar-check"></i><strong>{{ $technician->technician_appointments_count }}</strong> jobs today</span>@if($technician->technicianLocation)<span><i class="ph ph-navigation-arrow"></i><strong>{{ $technician->technicianLocation->recorded_at->diffForHumans() }}</strong> GPS updated</span><a class="text-link" href="https://www.google.com/maps/search/?api=1&query={{ $technician->technicianLocation->latitude }},{{ $technician->technicianLocation->longitude }}" target="_blank" rel="noopener">Open technician pin <i class="ph ph-arrow-up-right"></i></a>@else<span><i class="ph ph-map-pin-line"></i>No location shared</span>@endif</div><form class="admin-form" method="POST" action="{{ route('admin.technicians.update',$technician) }}">@csrf @method('PATCH')<div><label>Name</label><input name="name" value="{{ $technician->name }}" required></div><div class="field-grid"><div><label>Email</label><input type="email" name="email" value="{{ $technician->email }}" required></div><div><label>Phone</label><input name="phone" value="{{ $technician->phone }}" required></div></div><div><label>New password <span style="font-weight:400">(leave blank to keep)</span></label><input type="password" name="password"></div><label style="display:flex;align-items:center;gap:8px"><input style="width:auto;min-height:auto" type="checkbox" name="is_active" value="1" @checked($technician->is_active)> Account active</label><button class="button button-navy button-small">Save technician</button></form></section>@endforeach
    <section class="service-admin-card"><h2>Add technician</h2><p style="color:#6c8290;font-size:10px">Creates a separate mobile field login.</p><form class="admin-form" method="POST" action="{{ route('admin.technicians.store') }}">@csrf<div><label>Full name</label><input name="name" required></div><div><label>Email</label><input type="email" name="email" required></div><div><label>Phone</label><input name="phone" required></div><div><label>Temporary password</label><input type="password" name="password" minlength="8" required></div><button class="button button-cyan button-small">Create mobile account</button></form></section>
</div>
@endsection
