@extends('layouts.admin')
@php($title = 'Appointment '.$appointment->reference)
@section('content')
<div class="admin-top"><div><a class="text-link" href="{{ route('admin.appointments.index') }}"><i class="ph ph-arrow-left"></i> Appointments</a><h1 style="margin-top:7px">{{ $appointment->reference }}</h1><p>Booked {{ $appointment->created_at->format('M j, Y · g:i A') }} through {{ $appointment->source }}.</p></div><span class="status-badge status-{{ $appointment->status }}">{{ $appointment->status_label }}</span></div>
<div class="admin-detail-grid"><div class="side-stack">
    <section class="detail-block"><h2>Appointment details</h2><div class="detail-list"><div><span class="detail-label">Customer</span><span class="detail-value">{{ $appointment->customer->full_name }}</span></div><div><span class="detail-label">Contact</span><span class="detail-value">{{ $appointment->customer->phone }}<br>{{ $appointment->customer->email }}</span></div><div><span class="detail-label">Service</span><span class="detail-value">{{ $appointment->service->name }} · {{ $appointment->quantity }} {{ Str::plural('unit',$appointment->quantity) }}</span></div><div><span class="detail-label">Unit type</span><span class="detail-value">{{ $appointment->unit_type }}</span></div><div><span class="detail-label">Schedule</span><span class="detail-value">{{ $appointment->starts_at->format('D, M j, Y · g:i A') }}–{{ $appointment->ends_at->format('g:i A') }}</span></div><div><span class="detail-label">Total / payment</span><span class="detail-value">{{ $appointment->formatted_total }} · {{ $appointment->payment_status_label }}</span></div><div style="grid-column:1/-1"><span class="detail-label">Service address</span><span class="detail-value">{{ $appointment->address_line }}, {{ $appointment->barangay }}, Iligan City {{ $appointment->postal_code }}</span></div>@if($appointment->maps_url)<div style="grid-column:1/-1"><span class="detail-label">Customer-approved GPS pin</span><a class="text-link" href="{{ $appointment->maps_url }}" target="_blank" rel="noopener">Open exact location <i class="ph ph-arrow-up-right"></i></a></div>@endif @if($appointment->landmark)<div style="grid-column:1/-1"><span class="detail-label">Landmark</span><span class="detail-value">{{ $appointment->landmark }}</span></div>@endif @if($appointment->customer_notes)<div style="grid-column:1/-1"><span class="detail-label">Customer notes</span><span class="detail-value">{{ $appointment->customer_notes }}</span></div>@endif</div></section>
    <section class="detail-block"><h2>Price breakdown</h2><div class="detail-list"><div><span class="detail-label">Unit rate</span><span class="detail-value">{{ "\u{20B1}".number_format(($appointment->unit_price_centavos ?? 0)/100) }} × {{ $appointment->quantity }}</span></div><div><span class="detail-label">Customer total</span><span class="detail-value">{{ $appointment->formatted_total }}</span></div><div><span class="detail-label">Technician share</span><span class="detail-value">{{ $appointment->formatted_technician_share }}</span></div><div><span class="detail-label">Gross</span><span class="detail-value">{{ $appointment->formatted_gross }}</span></div></div></section>
    <section class="detail-block"><h2>Payment records</h2><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Method</th><th>Reference</th><th>Amount</th><th>Status</th></tr></thead><tbody>@foreach($appointment->payments as $payment)<tr><td><strong>{{ Str::title($payment->method) }}</strong>{{ $payment->provider ?: 'After service' }}</td><td>{{ $payment->reference ?: '—' }}</td><td><strong>{{ $payment->formatted_amount }}</strong></td><td><span class="status-badge status-{{ $payment->status }}">{{ Str::title($payment->status) }}</span></td></tr>@endforeach</tbody></table></div></section>
    <section class="detail-block"><h2>Booking history</h2><div class="timeline">@foreach($appointment->histories as $history)<div class="timeline-item"><strong>{{ Str::of($history->to_status)->replace('_',' ')->title() }}</strong><span>{{ $history->created_at->format('M j, Y · g:i A') }} by {{ $history->actor_name }}</span>@if($history->reason)<p>{{ $history->reason }}</p>@endif</div>@endforeach</div></section>
</div><aside class="side-stack">
    <section class="detail-block"><h2>Assign technician</h2><form class="admin-form" method="POST" action="{{ route('admin.appointments.assign',$appointment) }}">@csrf @method('PATCH')<div><label for="technician_id">Mobile technician account</label><select id="technician_id" name="technician_id"><option value="">Unassigned</option>@foreach($technicians as $technician)<option value="{{ $technician->id }}" @selected($appointment->technician_id===$technician->id)>{{ $technician->name }}</option>@endforeach</select></div><button class="button button-cyan button-small">Save assignment</button></form>@if($appointment->technician)<p style="color:#6c8290;font-size:10px;margin:12px 0 0">{{ $appointment->technician->name }} can see this job, approved GPS pin, and route details in the technician portal.</p>@endif</section>
    <section class="detail-block"><h2>Update status</h2><form class="admin-form" method="POST" action="{{ route('admin.appointments.status',$appointment) }}">@csrf @method('PATCH')<div><label for="status">Appointment status</label><select id="status" name="status">@foreach(['pending_confirmation','confirmed','assigned','in_progress','completed','cancelled','no_show'] as $status)<option value="{{ $status }}" @selected($appointment->status===$status)>{{ Str::of($status)->replace('_',' ')->title() }}</option>@endforeach</select></div><div><label for="reason">Reason / note</label><textarea id="reason" name="reason" placeholder="Optional update note"></textarea></div><button class="button button-navy button-small">Save status</button></form></section>
    <section class="detail-block"><h2>Reschedule</h2><form class="admin-form" method="POST" action="{{ route('admin.appointments.reschedule',$appointment) }}">@csrf @method('PATCH')<div><label for="appointment_date">Date</label><input id="appointment_date" type="date" name="appointment_date" value="{{ $appointment->starts_at->format('Y-m-d') }}" min="{{ today()->format('Y-m-d') }}" required></div><div><label for="appointment_time">Arrival time</label><select id="appointment_time" name="appointment_time">@foreach(['08:00','10:00','13:00','15:00'] as $time)<option value="{{ $time }}" @selected($appointment->starts_at->format('H:i')===$time)>{{ \Carbon\Carbon::createFromFormat('H:i',$time)->format('g:i A') }}</option>@endforeach</select></div><button class="button button-ghost button-small">Update schedule</button></form></section>
    <section class="detail-block"><h2>Customer manage link</h2><p style="color:#6c8290;font-size:10px">Open the same private view available to the customer.</p><a class="button button-ghost button-small" href="{{ route('booking.manage',$appointment->manage_token) }}" target="_blank">Open private link <i class="ph ph-arrow-up-right"></i></a></section>
</aside></div>
@endsection
