@extends('layouts.technician')
@php($title = 'My Jobs')
@section('content')
<section class="tech-welcome"><div><span>{{ now()->format('l, F j') }}</span><h1>Hello, {{ Str::before($technician->name,' ') }}.</h1><p>You have {{ $todayAppointments->count() }} {{ Str::plural('job',$todayAppointments->count()) }} assigned today.</p></div><div class="tech-shift-badge"><i class="ph ph-briefcase"></i> Field view</div></section>

<section class="tech-location-card" data-tech-tools data-location-url="{{ route('technician.location.store') }}" data-dashboard-url="{{ route('technician.dashboard') }}">
    <div class="tech-location-icon"><i class="ph ph-navigation-arrow"></i></div><div><h2>Location and route tools</h2><p>Your location is shared only while this page is open and you switch sharing on. It helps the office coordinate field work and starts navigation from where you are without changing customer appointment times.</p><span data-tech-location-status>@if($lastLocation)Last shared {{ $lastLocation->recorded_at->diffForHumans() }}@else Location sharing is off.@endif</span></div><div class="tech-location-actions"><button class="button button-yellow button-small" type="button" data-tech-location><i class="ph ph-crosshair"></i> Share live location</button><button class="button button-ghost button-small" type="button" data-route-optimize><i class="ph ph-path"></i> Optimize from here</button></div>
</section>

<section class="tech-section"><div class="tech-section-heading"><div><span class="eyebrow">Today’s suggested route</span><h2>Time-aware stops</h2></div>@if($directionsUrl)<a class="button button-navy button-small" href="{{ $directionsUrl }}" target="_blank" rel="noopener">Open full route <i class="ph ph-arrow-up-right"></i></a>@endif</div><div class="tech-route-list">@forelse($optimizedRoute as $appointment)<article class="tech-job-card"><div class="route-number">{{ $loop->iteration }}</div><div class="tech-job-main"><div class="tech-job-top"><div><span>{{ $appointment->starts_at->format('g:i A') }} · {{ $appointment->barangay }}</span><h3>{{ $appointment->customer->full_name }}</h3></div><span class="status-badge status-{{ $appointment->status }}">{{ $appointment->status_label }}</span></div><p><i class="ph ph-broom"></i>{{ $appointment->service->name }} · {{ $appointment->quantity }} {{ Str::plural('unit',$appointment->quantity) }} · {{ $appointment->unit_type }}</p><p><i class="ph ph-wallet"></i>Technician share: {{ $appointment->formatted_technician_share }}</p><p><i class="ph ph-map-pin"></i>{{ $appointment->address_line }}, {{ $appointment->barangay }}, Iligan City</p>@if($appointment->customer_notes)<div class="tech-note"><i class="ph ph-note"></i>{{ $appointment->customer_notes }}</div>@endif<div class="tech-job-actions">@if($appointment->maps_url)<a class="button button-ghost button-small" href="{{ $appointment->maps_url }}" target="_blank" rel="noopener"><i class="ph ph-navigation-arrow"></i> Customer pin</a>@else<span class="gps-missing"><i class="ph ph-map-pin-line"></i> Address only</span>@endif<form method="POST" action="{{ route('technician.appointments.status',$appointment) }}">@csrf @method('PATCH')<select name="status">@foreach(['assigned','in_progress','completed'] as $status)<option value="{{ $status }}" @selected($appointment->status===$status)>{{ Str::of($status)->replace('_',' ')->title() }}</option>@endforeach</select><button class="button button-navy button-small">Update</button></form></div></div></article>@empty<div class="tech-empty"><i class="ph ph-coffee"></i><h3>No assigned jobs today</h3><p>Your next assigned appointment will appear here.</p></div>@endforelse</div></section>

<section class="tech-section"><div class="tech-section-heading"><div><span class="eyebrow">Next 14 days</span><h2>Upcoming assignments</h2></div></div><div class="tech-upcoming-list">@forelse($appointments as $appointment)<div><span class="tech-date-box"><strong>{{ $appointment->starts_at->format('d') }}</strong>{{ $appointment->starts_at->format('M') }}</span><span><strong>{{ $appointment->customer->full_name }}</strong><small>{{ $appointment->starts_at->format('D · g:i A') }} · {{ $appointment->barangay }}</small></span><span class="status-badge status-{{ $appointment->status }}">{{ $appointment->status_label }}</span></div>@empty<div class="tech-empty">No upcoming assignments.</div>@endforelse</div></section>
@endsection
